In [13]:
# Import packages.
import pandas as pd
import numpy as np
import os

In [43]:
# Load data.

# define file path, separate for organization.
netflix_prize_filepath = "/Users/calynguyen/Downloads/data/Netfli_prize/combined_data_1.txt"

# data is separated by "," so we can use pd.read_csv().
rows = []
movie_id = None

with open(netflix_prize_filepath, "r") as file:
    for line in file:
        line = line.strip()

        if line.endswith(":"):
            movie_id = line.replace(":", "")
        
        else:
            customer_id, movie_rating, date = line.split(",")
            rows.append([movie_id, customer_id, movie_rating, date ])
            
netflix_prize_data = pd.DataFrame(
    rows,
    columns = ["movie_id", "customer_id", "movie_rating", "date"]  
)

# Grab first couple rows of data for preview.
netflix_prize_data.head()

  movie_id customer_id movie_rating        date
0        1     1488844            3  2005-09-06
1        1      822109            5  2005-05-13
2        1      885013            4  2005-10-19
3        1       30878            4  2005-12-26
4        1      823519            3  2004-05-03

In [47]:
# Convert data to useable format.
netflix_prize_data["movie_id"] = netflix_prize_data["movie_id"].astype(int)
netflix_prize_data["customer_id"] = netflix_prize_data["customer_id"].astype(int)
netflix_prize_data["movie_rating"] = netflix_prize_data["movie_rating"].astype(float)
netflix_prize_data["date"] = pd.to_datetime(netflix_prize_data["date"])

# Feature Engineer.
netflix_prize_data["avg_customer_rating"] = netflix_prize_data.groupby("customer_id")["movie_rating"].transform("mean")
netflix_prize_data["avg_date_rating"] = netflix_prize_data.groupby("date")["movie_rating"].transform("mean")
netflix_prize_data["total_number_of_ratings_per_date"] = netflix_prize_data.groupby("date")["movie_rating"].transform("count")
netflix_prize_data["total_number_of_ratings_per_movie"] = netflix_prize_data.groupby("movie_id")["movie_rating"].transform("count")

# Preview.
netflix_prize_data.head()

,movie_id,customer_id,movie_rating,date,avg_customer_rating,avg_date_rating,total_number_of_ratings_per_date,total_number_of_ratings_per_movie
0,1,1488844,3.0,2005-09-06,3.253308,3.674945,45986,547
1,1,822109,5.0,2005-05-13,4.083333,3.662106,30699,547
2,1,885013,4.0,2005-10-19,3.873563,3.729616,40313,547
3,1,30878,4.0,2005-12-26,3.634304,3.685429,11832,547
4,1,823519,3.0,2004-05-03,3.917197,3.579395,27993,547